### ISSUE TITLE
Endurance needs to be Santé

### ISSUE THREAD

**Issue by Xaratas** [r-e-d/poe2-fr#2]
PoE 2 does not use Endurance. All Health is Santé.
Examples: gui.stringtable IDs: 2432, 2433 
possible more

abilities.stringtable ID: 863
Berseker,which is a subclass, should not be translated into "Barbare", how is already used for the name of the class. Please replace Berserker by its correct French translation. --> Looks very wrong. Didn't check if you fixed this already

**Comment by r-e-d** [comment]
Thanks for the info. Health should be fixed now.

I'll fix Berserker later.

**Comment by r-e-d** [comment]
Berserker should be fixed now.
